# Python Type Conversion Examples
# int, float, complex, str, list, tuple, range, bool, dict, set, frozenset, None

# Integer type Conversion
# print(int(25))
# print(float(25))
# print(complex(25))
# print(str(25))
# print(list(25))
# print(tuple(25))
# print(range(25))
# print(bool(25))
# print(dict(25))
# print(set(25))
# print(frozenset(25))
# print(None(25))

# Float type Conversion
# print(int(25.5))
# print(float(25.5))
# print(complex(25.5))
# print(str(25.5))
# print(list(25.5))
# print(tuple(25.5))
# print(range(25.5))
# print(bool(25.5))
# print(dict(25.5))
# print(set(25.5))
# print(frozenset(25.5))
# print(None(25.5))

# Complex type Conversion
# print(int(25+5j))
# print(float(25+5j))
# print(complex(25+5j))
# print(str(25+5j))
# print(list(25+5j))
# print(tuple(25+5j))
# print(range(25+5j))
# print(bool(25+5j))
# print(dict(25+5j))
# print(set(25+5j))
# print(frozenset(25+5j))
# print(None(25+5j))

# String type Conversion
# print(int("25"))
# print(float("25"))
# print(complex("25"))
# print(str("25"))
# print(list("25"))
# print(tuple("25"))
# print(range("25"))
# print(bool("25"))
# print(dict("25"))
# print(set("25"))
# print(frozenset("25"))
# print(None("25"))

# List type Conversion
# print(int([25]))
# print(float([25]))
# print(complex([25]))
# print(str([25]))
# print(list([25]))
# print(tuple([25]))
# print(range(25))
# print(bool([25]))
# print(dict([25]))
# print(set([25]))
# print(frozenset([25]))
# print(None([25]))

# Tuple type Conversion
# print(int((25,)))
# print(float((25,)))
# print(complex((25,)))
# print(str((25,)))
# print(list((25,)))
# print(tuple((25,)))
# print(range(25))
# print(bool((25,)))
# print(dict((25,)))
# print(set((25,)))
# print(frozenset((25,)))
# print(None((25,)))

# Range type Conversion
# print(int(range(25)))
# print(float(range(25)))
# print(complex(range(25)))
# print(str(range(25)))
# print(list(range(25)))
# print(tuple(range(25)))
# print(range(25))
# print(bool(range(25)))
# print(dict(range(25)))
# print(set(range(25)))
# print(frozenset(range(25)))
# print(None(range(25)))

# Boolean type Conversion
# print(int(True))
# print(float(True))
# print(complex(True))
# print(str(True))
# print(list(True))
# print(tuple(True))
# print(range(True))
# print(bool(True))
# print(dict(True))
# print(set(True))
# print(frozenset(True))
# print(None(True))

# Dictionary type Conversion
# print(int({"key": 25}))
# print(float({"key": 25}))
# print(complex({"key": 25}))
# print(str({"key": 25}))
# print(list({"key": 25}))
# print(tuple({"key": 25}))
# print(range({"key": 25}))
# print(bool({"key": 25}))
# print(dict({"key": 25}))
# print(set({"key": 25}))
# print(frozenset({"key": 25}))
# print(None({"key": 25}))

# Set type Conversion
# print(int({25}))
# print(float({25}))
# print(complex({25}))
# print(str({25}))
# print(list({25}))
# print(tuple({25}))
# print(range({25}))
# print(bool({25}))
# print(dict({25}))
# print(set({25}))
# print(frozenset({25}))
# print(None({25}))

# Frozenset type Conversion
# print(int(frozenset([25])))
# print(float(frozenset([25])))
# print(complex(frozenset([25])))
# print(str(frozenset([25])))
# print(list(frozenset([25])))
# print(tuple(frozenset([25])))
# print(range(frozenset([25])))
# print(bool(frozenset([25])))
# print(dict(frozenset([25])))
# print(set(frozenset([25])))
# print(frozenset(frozenset([25])))
# print(None(frozenset([25])))

# None type Conversion
# print(int(None))
# print(float(None))
# print(complex(None))
# print(str(None))
# print(list(None))
# print(tuple(None))
# print(range(None))
print(bool(None))
# print(dict(None))
# print(set(None))
# print(frozenset(None))
# print(None(None))