# list1 = [1, 2, 5, 7, 9, 3, 'str1', 6 ,7]

# Append
# list1.append(9)
# print(list1)
# list1.append([2, 3, 4])
# print(list1)

# Extend
# list1.extend([71, 88, 92])
# print(list1)

# Insert
# list1.insert(3,[7, 6, 5, 4])
# print(list1)

# Clear
# list1.clear()
# print(list1)

# Pop
# list1.pop()
# print(list1)
# ele = list1.pop()

# Remove
# list1.remove(3)
# print(list1)

# Reverse
# list1.reverse()
# print(list1)

# Sort
# list1 = [1, 47, 46, 9, 5, 78, 23, 56, 8]
# list1.sort()
# print(list1)
# list1.sort(reverse = True)
# print(list1)